site_name: Unix Lab - Don Bosco Institute of Technology, Mumbai
theme:
  name: material
  custom_dir: overrides
  features:
  - navigation.tabs
  - navigation.sections

plugins:
  - mkdocs-simple-hooks:
      hooks:
        on_files: "build.nav:on_files"

docs_dir: courses

markdown_extensions:
  - meta
  - fenced_code

repo_url: https://github.com/tayyabsayyad/unix-mkdocs


extra_css:
  - assets/codemirror/lib/codemirror.css
  - assets/style.css

extra_javascript:
  - assets/codemirror/lib/codemirror.js
  - assets/codemirror/addon/mode/simple.js
  - assets/codemirror/mode/python/python.js
  - assets/codemirror/mode/rust/rust.js
  - assets/codemirror/mode/go/go.js
  - assets/codemirror/keymap/sublime.js
  - assets/codemirror/addon/edit/matchbrackets.js
  - assets/codemirror/addon/comment/comment.js
  - https://code.jquery.com/jquery-3.6.0.min.js
